export enum Service {
    GENESIS_GENERATE = 'GENESIS_GENERATE',
    BLOCK_GENERATE = 'BLOCK_GENERATE',
    BLOCK_STATS = 'BLOCK_STATS',
    CHAIN_VERIFY = 'CHAIN_VERIFY',
    CREATE_BLOCKS = 'CREATE_BLOCKS'
}